# Generated by Django 5.0.4 on 2024-04-22 17:02

import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iniciopage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='iniciopage',
            name='imagenCarousel',
        ),
        migrations.AddField(
            model_name='iniciopage',
            name='carouselImages',
            field=wagtail.fields.StreamField([('carouselImage', wagtail.images.blocks.ImageChooserBlock())], blank=True),
        ),
        migrations.AddField(
            model_name='iniciopage',
            name='services',
            field=wagtail.fields.StreamField([('service', wagtail.blocks.PageChooserBlock(page_type=['servicio.servicio']))], blank=True),
        ),
    ]
