# Generated by Django 5.0.4 on 2024-04-24 10:09

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_remove_iniciopage_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iniciopage',
            name='services',
        ),
        migrations.AddField(
            model_name='iniciopage',
            name='servicios',
            field=wagtail.fields.StreamField([('servicio', wagtail.blocks.PageChooserBlock(page_type=['servicio.servicio']))], blank=True),
        ),
    ]
