# Generated by Django 5.0.4 on 2024-05-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='carousel_images',
            field=models.ManyToManyField(blank=True, help_text='Immagini per il carousel in homepage', related_name='+', to='wagtailimages.image'),
        ),
    ]
