# Generated by Django 5.0.4 on 2024-05-03 15:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviciolistapage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
