# Generated by Django 5.0.4 on 2024-05-08 08:48

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_alter_card_body_alter_servicio_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='subapartadoslist',
            field=wagtail.fields.StreamField([('subapartados', wagtail.blocks.PageChooserBlock(page_type=['servicio.subapartados']))], blank=True, null=True),
        ),
    ]
