# Generated by Django 5.0.4 on 2024-05-20 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_alter_servicio_subapartadoslist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
    ]
