# Generated by Django 5.0.4 on 2024-05-06 11:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0002_contratpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.DeleteModel(
            name='cardspagr',
        ),
    ]
